### ISSUE TITLE
Support two new runtimes: `nodejs8` and `python37`

### ISSUE THREAD

**Issue by jubobs** [serverless/serverless-google-cloudfunctions#119]
# This is a Feature Proposal

Add support for newly supported runtimes `nodejs8` and `python37`.

## Description

Google recently [announced](https://cloudplatform.googleblog.com/2018/07/bringing-the-best-of-serverless-to-you.html) support for two more runtimes (`nodejs8` and `python37`), in addition to `nodejs`. This plugin should support those two additional runtimes as well.

Support for the Python runtime is particularly desirable to those who don't particularly enjoy Node.js... cough cough...

**Comment by pestrov** [comment]
Are there any clues to how we could help to make a pull request on this issue? I would be able, provided the core team could elaborate on what to focus on.

**Comment by henry74** [comment]
Pull the latest serverless release 1.30.x - they added nodejs8 support

**Comment by Benoss** [comment]
What about python 3.7 ?

**Comment by pickypg** [comment]
https://github.com/serverless/serverless-google-cloudfunctions/pull/114/files#diff-27d6eb1652c0c3d836eed4df04585a51R41

I'm pretty sure this PR being merged silently enables any runtime, even though its goal was to enable `nodejs8` (by default!).

**Comment by jubobs** [comment]
I can confirm that `nodejs8` support is in place, though still undocumented. Here is a MWE:

index.js
```javascript
exports.http = (req, res) => {
  let message = req.query.message || req.body.message || 'Hello World!';
  res.status(200).send(message);
};
```

package.json
```json
{
  "name": "sample-http",
  "version": "0.0.1",
  "dependencies": {
    "serverless": "^1.32.0",
    "serverless-google-cloudfunctions": "^2.2.0"
  }
}
```

serverless.yaml
```yaml
service: my-service

provider:
  name: google
  runtime: nodejs8
  project: my-project
  credentials: ~/.gcloud/keyfile.json
  region: us-central1

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
```

**Comment by jubobs** [comment]
I can also confirm that `python37` support is in place, though also still undocumented. Here is a MWE:

main.py
```python
def hello(request):
    """Responds to any HTTP request.
    Args:
        request (flask.Request): HTTP request object.
    Returns:
        The response text or any set of values that can be turned into a
        Response object using
        `make_response <http://flask.pocoo.org/docs/0.12/api/#flask.Flask.make_response>`.
    """
    request_json = request.get_json()
    if request.args and 'message' in request.args:
        return request.args.get('message')
    elif request_json and 'message' in request_json:
        return request_json['message']
    else:
        return f'Hello World!'
```

serverless.yaml
```
service: my-service

provider:
  name: google
  runtime: python37
  project: my-project
  credentials: ~/.gcloud/keyfile.json
  region: us-central1

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: hello
    events:
      - http: path
```
