### ISSUE TITLE
support GOOGLE_APPLICATION_CREDENTIALS variable for authentication

### ISSUE THREAD

**Issue by philsch** [serverless/serverless-google-cloudfunctions#122]
# This is a feature request
At the moment Google Cloud credentials have to be set via the `provider.credentials` parameter. It would be nice if the env variable `GOOGLE_APPLICATION_CREDENTIALS=<path-to-json>` as described in the [Google Cloud Documentation](https://cloud.google.com/docs/authentication/getting-started) is supported.

## Example

1. set the path to the credentials as environment variable `export GOOGLE_APPLICATION_CREDENTIALS=~/google.json`
1. the following provider definition does not throw an Exception
```
provider:
  name: google
  runtime: nodejs
  project: my-project
  # credentials: credentials are not set explicitly
```
