### ISSUE TITLE
Error on attempt to deploy with default settings: "region us-east-1 is not supported."

### ISSUE THREAD

**Issue by Xotabu4** [serverless/serverless-google-cloudfunctions#124]
serverless.yml
```
service: gcf-nodejs 

provider:
  name: google
  runtime: nodejs
  project: embarrassingly-parallel
  credentials: ./keys/googlekey.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  my-test-function:
    handler: first
    events:
      - http: path
```

Log

```
> serverless deploy --region us-east1

(node:96085) ExperimentalWarning: The fs.promises API is experimental
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "embarrassingly-parallel-mocha"...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...
..
  Error --------------------------------------------------

  Deployment failed: RESOURCE_ERROR

     {"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"region","description":"region us-east-1 is not supported."}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1beta2/projects/embarrassingly-parallel/locations/us-east1/functions/first","httpMethod":"PUT"}}

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.1.0
     Serverless Version:     1.32.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! embarrassingly-parallel-mocha@1.0.0 deploy: `serverless deploy --region us-east1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the embarrassingly-parallel-mocha@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oleksandrkhotemskyi/.npm/_logs/2018-10-15T18_29_28_829Z-debug.log
```

I noticed that region is actually named: 'us-region1' not 'us-region-1'

So when i manualy quickly updated (right in the middle of script running) 
configuration-template-update.yml location property:
```
    properties:
      location: us-east1
```

deployment passed successfully.

Seems like --region property is ignored?
