### ISSUE TITLE
Function "rod-MyFunctionName" doesn't exist in this Service

### ISSUE THREAD

**Issue by JonasLaux** [serverless/serverless-google-cloudfunctions#142]
As explained in https://github.com/serverless/serverless/issues/5557
i have Problems with my CI and the Google Functions.
I'm using Version 2.2.1

**Comment by pmuens** [comment]
Hey @JonasLaux thanks again for opening this issue.

I tried to reproduce it today running the latest version of the Serverless Framework (v1.34.1) and the latest version of this plugin (v2.3.1).

Here's the `serverless.yml` I've used (it's based on the `serverless.yml` you've shared in the initial writeup):

```yml
service: serverless

provider:
  name: google
  runtime: nodejs
  project: some-project
  region: europe-west1
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/some-project.json
  environment:
    SOME_VAR: foo

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  myFunction:
    handler: myFunction
    events:
      - http: path
  mySecondFunction:
    handler: mySecondFunction
    events:
      - http: path
  myThirdFunction:
    handler: myThirdFunction
    events:
      - http: path
```

Unfortunately I wasn't able to reproduce. Here's the output I get when deploying / removing:

```
[~/Desktop/code.nosync/serverless/tmp/google]$ ../../bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "myFunction"...
Serverless: Compiling function "mySecondFunction"...
Serverless: Compiling function "myThirdFunction"...
Serverless: Creating deployment...
Serverless: Checking deployment create progress...
.
Serverless: Done...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...
..........................
Serverless: Done...
Service Information
service: serverless
project: some-project
stage: dev
region: europe-west1

Deployed functions
myFunction
  https://europe-west1-some-project.cloudfunctions.net/myFunction
mySecondFunction
  https://europe-west1-some-project.cloudfunctions.net/mySecondFunction
myThirdFunction
  https://europe-west1-some-project.cloudfunctions.net/myThirdFunction


[~/Desktop/code.nosync/serverless/tmp/google]$ ../../bin/serverless remove
Serverless: Removing artifacts in deployment bucket...
Serverless: Removing deployment...
Serverless: Checking deployment remove progress...
..
Serverless: Done...
```

Can you update the plugin to use that latest version and try again?
