### ISSUE TITLE
Is Firestore Event Triggers supported?

### ISSUE THREAD

**Issue by dsjacobsen** [serverless/serverless-google-cloudfunctions#146]
Can Firestore Event Triggers be used with the Serverless framework? 

I want to use Cloud Firestore triggers, but unsure if it’s support, and if it is, then how I correctly specify the event in the serverless.yml file?

An example of a function that should trigger event when any changes to a document happens. From here: https://firebase.google.com/docs/functions/firestore-events

Note: I am importing functions from firebase in a separate file and then importing it in my index.js.

```
exports.firestoreEvents = functions.firestore
   .document(‘users/marie’).onWrite((change, context) => {
     // ... Your code here
   });
```

If supported, how do I configure it in serverless.yml?

```
 firestoreEvents:
   handler: firestoreEvents
   events:
     - event:
       ????
```

**Comment by pmuens** [comment]
Hey @dsjacobsen thanks for opening :+1:

The [`event` event](https://cloud.google.com/functions/docs/concepts/events-triggers) can be any event which is in turn handled by a [Background Function](https://cloud.google.com/functions/docs/writing/background).

According to the [`event` docs](https://cloud.google.com/functions/docs/concepts/events-triggers) those could be firebase events as well.

I haven't tried it but the definition should look something like this:

```yml
firestoreEvents:
  handler: firestoreEvents
  events:
    - event:
      resource: google.firebase.foo.bar
      eventType: providers/google.firebase.analytics/eventTypes/foo.bar
```

**Comment by marianofino** [comment]
Hello @dsjacobsen @pmuens 
For triggering a function upon a Firestore document change you should write something like this in your serverless.yml file:
```
myFunction:
  handler: myFunction
  events:
    - event:
        eventType: providers/cloud.firestore/eventTypes/document.update
        resource: projects/<project-id>/databases/(default)/documents/<path-to-document>
```
I have written an article on how to use Serverless Framework with Firebase triggers: https://medium.com/ponce-agtech/using-firebase-triggers-in-serverless-framework-ad99594b86fa 

Hope it helps ;)
