### ISSUE TITLE
Deploying other GCP resources but without any functions

### ISSUE THREAD

**Issue by jieren172** [serverless/serverless-google-cloudfunctions#163]
Hi,

I am currently trying to use serverless framework on google cloud. In some use cases, I don't need to deploy any functions in my stack, but other resources like Storage buckets. The reason I am doing this is because of the advantages of all kinds of variable placeholders and yml files referencing with serverless framework, which make much easier to build up the deployment templates.

So I want something like this:

```
service: test

provider:
  name: google
  project: 'project-test'
  region: 'europe-west1'

plugins:
  - serverless-google-cloudfunctions

# --- no funtions parts ------

resources:
  resources:
    - type: storage.v1.bucket
      name: test-bucket        
```

But it seems it is currently not possible to do that, because the plugin always tries to search defined functions, and throws error if there's none of them.

I am sure that with AWS it is possible to deploy resources without any lambda in it with serverless framework. 

I think It would be very nice if we can have this feature in the plugin !

Thx
