### ISSUE TITLE
Gcloud -  instance does not match any allowed primitive type

### ISSUE THREAD

**Issue by AdamZaczek** [serverless/serverless-google-cloudfunctions#171]
I'm getting the following error:
Deployment failed: CONDITION_NOT_MET

     "/httpsTrigger/url": domain: validation; keyword: type; message: instance does not match any allowed primitive type; allowed: ["string"]; found: "object"

This is my serverless.yml
```
service: xyz
tenant: adamzaczek
app: xyz
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-google-cloudfunctions
custom:
  webpack:
    includeModules: true
    webpackConfig: ./webpack.config.js
  serverless-offline:
    port: 8000

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

provider:
  name: google
  runtime: nodejs10
  project: xyz-242209
  credentials: .gcloud/keyfile.json
  region: us-central1
functions:
  graphql:
    handler: handler
    events:
      - http:
          path: graphql
  playground:
    handler: handler
    events:
      - http:
          path: playground
          method: get
```
I've been very happy with using serverless and aws.
I tried to make gcloud work with serverless for the entire day with no success. This is the issue that has stopped me for good.

**Comment by alexrhogue** [comment]
Did you ever figure this out?  I'm having the same issue

**Comment by AdamZaczek** [comment]
Yes, despite the claims serverless does not work with GCloud.

**Comment by csplinter** [comment]
I was hitting this issue today when I had my function structured like my AWS serverless.yml
```
functions:
  createCatalog:
    handler: handler.createCatalog 
    events: 
      - http:
          path: catalog/create
          method: post
```

I got passed this error by changing it to the following in my GCP serverless.yml. Apparently you don't need to specify method for GCP in serverless.yml. See [this doc](https://serverless.com/framework/docs/providers/google/guide/events#configuration).
```
functions:
  createCatalog:
    handler: createCatalog 
    events: 
      - http: catalog/create
```
