### ISSUE TITLE
Support Google Schedules for serverless functions (cron)

### ISSUE THREAD

**Issue by timwsuqld** [serverless/serverless-google-cloudfunctions#174]
Google supports using pub/sub events to trigger functions, which can be sent with Cloud Scheduler (https://cloud.google.com/scheduler/) for a proper "cron". The AWS support already exists (https://serverless.com/framework/docs/providers/aws/events/schedule/)  so it would be great if we could have Google's scheduler supported as well, for a clean deployment with the serverless framework.

**Comment by deemetree-at-satelligence** [comment]
Fully agree, that'd be great! 
For whoever is interested and if it might help out, that's how I managed to set it up!   

```yaml
# serverless.yml
# ...


functions:
  foo_generator:
    handler: foo_generator
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project}/topics/<FOO_TOPIC_NAME>'

resources:
  resources:
    - type: pubsub.v1.topic
      name: <FOO_TOPIC_NAME>
      properties:
        topic: <FOO_TOPIC_NAME>
    - type: gcp-types/cloudscheduler-v1:projects.locations.jobs
      name: <YOUR_JOB_NAME>
      properties:
        parent: projects/${self:provider.project}/locations/${self:provider.region}
        name: <YOUR_JOB_NAME>
        description: "Produce mock data for services"
        schedule: "0 2 * * *" # this controls the CRON schedule of your function invocations
        timeZone: "Europe/Amsterdam"
        pubsubTarget:
          topicName: projects/${self:provider.project}/topics/<FOO_TOPIC_NAME>
          data: aGVsbG8hCg== # base64 encoded "hello!" that will be passed as PubSub message payload
```

This is based on the description here: https://cloud.google.com/scheduler/docs/tut-pub-sub and discussion here that mentions that [Google Deployment Manager]() supports [gcp-types/cloudscheduler-v1:projects.locations.jobs](https://cloud.google.com/scheduler/docs/reference/rest/v1/projects.locations.jobs) - see  [google issue tracker discussion](https://issuetracker.google.com/issues/123013878). 

Hope it helps someone! (And later having it abstracted would be cool! Maybe a separate plugin or part of this one?)
