### ISSUE TITLE
Add max number of invocations per function

### ISSUE THREAD

**Issue by roberthmiller** [serverless/serverless-google-cloudfunctions#177]
Within the google cloud CLI, we are able to specify `--max-instances`, but within serverless I cannot find an option to do so.

Reference: https://cloud.google.com/functions/docs/max-instances

**Comment by profoundpanda** [comment]
You can add `maxInstances` in the serverless.yaml file now.

eg:

```
functions:
  my-function:
     handler: my-exported-function-name
     events: 
        - http: path
     maxInstances: 10
```
