### ISSUE TITLE
Setting a label causes an INVALID_ARGUMENT error

### ISSUE THREAD

**Issue by gretro** [serverless/serverless-google-cloudfunctions#185]
When I deploy a serverless service with a label defined, I'm getting an **INVALID_ARGUMENT** error when updating a function. I get the same behavior if the label is defined on the function directly and if the label is defined on the provider.

When I remove the label property, the deployment works as expected.

Here is the error I get:
```json
{
   "ResourceType":"cloudfunctions.v1beta2.function",
   "ResourceErrorCode":"400",
   "ResourceErrorMessage":{
      "code":400,
      "message":"The request has errors",
      "status":"INVALID_ARGUMENT",
      "details":[
         {
            "@type":"type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations":[
               {
                  "field":"labels",
                  "description":"labels {app=Serverless Spike} format is invalid"
               }
            ]
         }
      ],
      "statusMessage":"Bad Request",
      "requestPath":"https://cloudfunctions.googleapis.com/v1beta2/projects/<my-project>/locations/<my-location>/functions/test",
      "httpMethod":"PUT"
   }
}
```

And here is the Stack Trace:
```
Error: Deployment failed: RESOURCE_ERROR

     {"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"labels","description":"labels {app=Serverless Spike} format is invalid"}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1beta2/projects/<my-project>/locations/<my-location>/functions/test","httpMethod":"PUT"}}
    at throwErrorIfDeploymentFails (/Users/gretro/wks/spike-serverless/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:74:11)
    at provider.request.then (/Users/gretro/wks/spike-serverless/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:43:17)
From previous event:
    at GoogleDeploy.monitorDeployment (/Users/gretro/wks/spike-serverless/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:18:12)
    at provider.request.then (/Users/gretro/wks/spike-serverless/node_modules/serverless-google-cloudfunctions/deploy/lib/updateDeployment.js:54:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.9.0
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.11
     Platform SDK Version:      2.1.2
```

Here is my `serverless.yml`:
```yaml
service: spike-serverless

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: <my-region>
  project: <my-project>
  credentials: <my-credentials>
  memorySize: 128

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  test:
    handler: test
    events:
      - http: http
    labels:
      app: Serverless Spike
```

Any idea how to solve this issue? Am I doing anything wrong or is it an update from the GCP API that broke this feature?

Thanks
