### ISSUE TITLE
How to deploy public function on GCF?

### ISSUE THREAD

**Issue by Micka33** [serverless/serverless-google-cloudfunctions#205]
I can't find the answer anywhere in the documentation. Feel free to point it to me.
```sh
$> serverless
```
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.67.0 (standalone)
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```
```yml
# serverless.yml
service: my-name

provider:
  name: google
  runtime: nodejs8
  region: europe-west1
  project: project-123456
  credentials: ~/path/to/secret.json

plugins:
  - serverless-google-cloudfunctions
package:
  excludeDevDependencies: true
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  my_name:
    handler: my_name_http
    memorySize: 128
    timeout: 60s
    events:
      - http: path
    labels:
      application: my-name
    environment:
      PROJECT_ID: ${self:provider.project}
```
Since the last `serverless upgrade`, my functions are deployed without the "Cloud function invoker" role set to "allUsers".
<img width="200" alt="Screenshot 2020-03-30 at 16 55 47" src="https://user-images.githubusercontent.com/3918958/77927630-bd583180-72a7-11ea-8b4d-f575a562c8ed.png">

By the way, I can't find anywhere in the documentation how to set it in `serverless.yml`.  
Can you help me?

N.B.: Of course, I did set it in the Google Cloud Console UI and the function works perfectly. But then, I can no longer do `serverless deploy`. It displays the following error:
```sh
$> serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "my-name"...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...
....
  Error --------------------------------------------------

  Error: Deployment failed: RESOURCE_ERROR

       {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Invalid JSON payload received. Unknown name \"location\" at 'function': Cannot find field.","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"function","description":"Invalid JSON payload received. Unknown name \"location\" at 'function': Cannot find field."}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/project-123456/locations/europe-west1/functions/my-name-dev-my-name","httpMethod":"PATCH"}}
      at throwErrorIfDeploymentFails (/Users/username/Documents/remotal/remotal-my-name/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:71:11)
      at /Users/username/Documents/remotal/remotal-my-name/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:42:17
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.67.0 (standalone)
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

**Comment by bao1018** [comment]
@Micka33 it caused by the location field not support anymore, please update the latest version and try again

**Comment by Micka33** [comment]
Either I don't understand what you mean by `update to latest version and try again` or you didn't read all my post.

1. What should I update to the latest version?
2. This error only occurs when I manually add a role to a google cloud function through the GCC UI and run `serverless deploy`.
3. I would like to understand how I can specify that I want the role `Cloud function invoker` set with `allUsers` when running `serverless deploy`.

**Comment by Micka33** [comment]
Up

**Comment by iSynthetica** [comment]
Have the same issue, after updated serverless and serverless-google-cloudfunctions have an error:
```
Error: Forbidden
Your client does not have permission to get URL /function from this server
```

**Comment by Micka33** [comment]
Does anyone know a way to setup `Cloud function invoker` to `allUsers` while deploying with serverless ?

**Comment by Trowsing** [comment]
Same here, only happens if you upgrade to version `3.0.0`, tried downgrading to `2.4.3` and everything was working again with the correct invoker.

**Comment by mwawrusch** [comment]
It would be nice to have a fix for this. Downgrading to 2.4.3 does not work anymore as Google ended support for the previous API, so we are stuck with 3.0.0. 

So what is the correct way to make a function publicly accessible with serverless?

**Comment by curtismenmuir** [comment]
I am using private cloud functions with Serverless v3.
I have setup a google cloud project which has a Gateway API (App Engine) to sit in front of the private cloud functions. To allow communication between gateway and cloud functions, I have created a Service Account with the `Cloud Function Invoker` permissions. The gateway will then use a JSON keyfile for that service account to generate an `ID Token` to be sent as bearer token in request to Cloud Functions.

**Comment by pramendra** [comment]
The issue is not able `setIamPolicy` after deployment.

[Solution]: https://www.serverless.com/framework/docs/providers/google/guide/functions#environment-variables

We should be able to configure IAM policy via serverless.yml; similar to AWS.

**Comment by zenati** [comment]
Up.

**Comment by andrx** [comment]
+1

**Comment by nover** [comment]
Also having this problem now after upgrading to google provider 3 here - any fix in the pipeline?

**Comment by frandiox** [comment]
Docs and commands to change this policy using `gcloud` are here: https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_function_invocation

```
gcloud functions add-iam-policy-binding FUNCTION_NAME \
 --member="allUsers" \
 --role="roles/cloudfunctions.invoker" \
 --project=YOUR_PROJECT_ID
```

The previous command needs to be run once per function. New deployments work after making functions public with this command.

Apparently, an equivalent to the `--allow-unauthenticated` flag is missing in SLS deploy.

**Comment by kevboutin** [comment]
This was very helpful @frandiox 

Here is what worked for me:

```
gcloud functions add-iam-policy-binding SERVICENAME-STAGE-FUNCTIONNAME \
    --member="allUsers" \
    --role="roles/cloudfunctions.invoker" \
    --project="PROJECT_ID" \
    --region="us-east1"
```

**Comment by buffolander** [comment]
When will this be available from the npm package? I see the latest version (3.1.0) was deployed 2 months ago

**Comment by edaniszewski** [comment]
The changes made in the above linked PR appear to not fully work (see  #222).  I'm working through a solution for it, but it does seem like more work needs to be done to get the  feature stable enough for a new release. I'll post an update once I make some progress.

**Comment by edaniszewski** [comment]
I've opened a PR for an alternative approach for IAM that I've tested  locally and seems to work. See: https://github.com/serverless/serverless-google-cloudfunctions/pull/223

**Comment by deemetree-at-satelligence** [comment]
Wanted to add my two-pence based on suggestions of @frandiox @kevboutin, I managed to set it up using sls hooks using this plugin: https://www.npmjs.com/package/serverless-plugin-scripts, works pretty nice for me (I have just one function at this point) but I can imagine it might not work in all cases. Here is the snippet:  
```yaml
service: YOUR-SERVICE-NAME

custom:
  stage: ${env:TIER, opt:stage, "dev"}
 # this comes from https://www.npmjs.com/package/serverless-plugin-scripts
  scripts:
    commands:
      make-public: gcloud functions add-iam-policy-binding ${self:service}-${self:provider.stage}-${opt:function, "helloWorld"} --member="allUsers" --role="roles/cloudfunctions.invoker" --project=${self:provider.project} --region=${self:provider.region} | xargs echo 
    hooks:
      'after:deploy:deploy': npx sls make-public --function=helloWorld
....
``` 
And then it automatically makes the specified functions public after deploy and otherwise I can run `sls make-public --function=<function-name>` at any time.
