### ISSUE TITLE
Serverless: Configuration error: Unrecognized provider 'google'

### ISSUE THREAD

**Issue by parkan** [serverless/serverless-google-cloudfunctions#232]
This is a bit of headscratcher. I followed the [guide](https://www.serverless.com/framework/docs/providers/google/guide/) but am getting an Unrecognized provider error, no google hits for this.

```
serverless create --template google-nodejs --path serverless-demo
cd serverless-demo
serverless plugin install --name serverless-google-cloudfunctions # guide said to only do npm install --save but that wouldn't have added the plugin to the serverless.yml, which makes me suspect the guide is not accurate
```

in serverless.yml I have (generated by the template plus my credentials/region)

```yaml
service: serverless-demo

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-east1
  project: my-project
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcp/credentials.json # contains the JSON downloaded from GCP with appropriate permissions 

plugins:
  - serverless-google-cloudfunctions
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
  # NOTE: the following uses an "event" event (pubSub event in this case).
  # Please create the corresponding resources in the Google Cloud
  # before deploying this service through Serverless
  #second:
  #  handler: event
  #  events:
  #    - event:
  #        eventType: providers/cloud.pubsub/eventTypes/topic.publish
  #        resource: projects/*/topics/my-topic
# you can define resources, templates etc. the same way you would in a
# Google Cloud deployment configuration
#resources:
#  resources:
#    - type: storage.v1.bucket
#      name: my-serverless-service-bucket
#  imports:
#    - path: my_template.jinja
```

```
$ serverless --version
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.1
$ node --version
v12.3.0
```

Running `serverless` anything generates the above error

I am not able to find any further steps in the docs, nor a way to list known providers. What am I missing?
