### ISSUE TITLE
No key or keyFile set

### ISSUE THREAD

**Issue by gsouf** [serverless/serverless-google-cloudfunctions#234]
Hi I'm trying to deploy to cloud functions. After running `serverless deploy` then I'm getting this error:

```
Error: No key or keyFile set.
```

I did setup the keyFile in the credentials as specified in the doc:

```
provider:
    name: google
    stage: dev
    runtime: nodejs10
    region: us-central1
    project: someporject
    credentials: ~/.config/gcloud/somekeyfile.json
```

Any idea?
Thanks

---

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.19.0
     Framework Version:         1.78.1
     Plugin Version:            3.7.0
     SDK Version:               2.3.1
     Components Version:        2.34.1
```
