### ISSUE TITLE
Question: Is their a serverless plugin hook for google cloud function deploy?

### ISSUE THREAD

**Issue by nspeet** [serverless/serverless-google-cloudfunctions#237]
AWS has hooks such as this.hooks = {
"aws:deploy:finalize:cleanup": this.afterDeploy.bind(this),
};

Are there similar hooks for GCP cloud function deploys?

**Comment by steinnat** [comment]
Found this:
@deemetree-at-satelligence said you could do use sls hooks using this plugin: https://www.npmjs.com/package/serverless-plugin-scripts

```
service: YOUR-SERVICE-NAME

custom:
  ...
 # this comes from https://www.npmjs.com/package/serverless-plugin-scripts
  scripts:
    commands:
      make-public: gcloud functions add-iam-policy-binding ${self:service}-${self:provider.stage}-${opt:function, "YOUR-DEFAULT-FUNCTION-NAME"} --member="allUsers" --role="roles/cloudfunctions.invoker" --project=${self:provider.project} --region=${self:provider.region} | xargs echo 
    hooks:
      'after:deploy:deploy': npx sls make-public --function=YOUR-FUNCTION-NAME
...
```
This hook automatically makes the specified functions public after deploy and otherwise you can run sls make-public --function=<function-name> at any time. Just an idea of how he uses hooks, hope this helps.
