### ISSUE TITLE
Flakey deploy...

### ISSUE THREAD

**Issue by jtslear** [serverless/serverless-google-cloudfunctions#73]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
After a first time deploy failed due to a bug in the function I created, serverless told me I broke things, as is expected.  I took corrective action and deployed again.  The deploy indicated a success, however the function source location was not properly updated.  Leaving me with a false positive that all is well.

* What did you expect should have happened?
The function source location should've been updated.

* What was the config you used?
Can be [found here](https://gist.github.com/jtslear/64dc84caffb67fdcf977a71b722a28d1)

* What stacktrace or error message from your provider did you see?
No stack trace, serverless indicated all is well.  Google on the other hand thinks differently, as the function remains to be pointed to the older source location.  I've attached a gist below with the gcloud output.

## Additional Data
* 2 buckets were created properly, the first one being the one with the failed code:
```
 projects % gsutil ls gs://sls-synk-dev-1495197075934/serverless/synk/dev/
gs://sls-synk-dev-1495197075934/serverless/synk/dev/1495197091614-2017-05-19T12:31:31.614Z/
gs://sls-synk-dev-1495197075934/serverless/synk/dev/1495197504769-2017-05-19T12:38:24.769Z/
```

*  However when describing the function after a deploy, we can see it's still configured to point to the incorrect source, instead of our new location.
* **Workaround**, kick off another deploy.  But the fact that this failed the first time, has me worried that something is causing this to fail improperly, and for obviously reasons, future deploys.
*   The full log of what I did [is here](https://gist.github.com/jtslear/63f128788cc258fd1cd79e3cfaca9afd)
* In the above log, the time serverless takes checking on the status of the update progress is significantly different during the deploy which did not update the source properly. [(line 53)](https://gist.github.com/jtslear/63f128788cc258fd1cd79e3cfaca9afd#file-full-output-log-L53)

* ***Serverless Framework Version you're using***: 1.13.2
* ***Operating System***: OSX
* ***serverless-google-cloudfunctions Version***: 1.0.0

**Comment by pmuens** [comment]
Hey @jtslear thanks for the very detailed issue description! 👍 

I tried to reproduce it. Here's what I did:

I created a new service based on the template and renamed the function in `index.js` from `http` to `https` to ensure that Google Cloud is not able to find the exported function.

I deployed the service (note this is a fresh deployment from scratch) and the deployment fails in the update phase with the same error message about a missing export like you've also encountered.

After that I changed the name back from `https` to `http` and re-deployed. I also got a super fast deployment (like you've got [here](https://gist.github.com/jtslear/63f128788cc258fd1cd79e3cfaca9afd#file-full-output-log-L53)), however the deployment succeeded and the function points to the correct location in the bucket.

Furthermore only one bucket was created for this specific service (even after re-deploying).

It seems like you're using v1.0.0. Do you pull this from `npm`? It seems like this bug is already fixed in the current `master`. Could you please use the version in `master` and try again to see if this bug is still around?

Thanks!

**Comment by jtslear** [comment]
So I pulled from master this time, however, I'm still able to recreate the above issue.  Please note, I'm only getting one bucket, which I believe is legit, it's the contents inside the bucket that are being updated, but the source value for the function is not.  I recreate the issue with the exact steps above and ended up with the below output.

The gcloud command is run after first deploy failed.  I then ran gsutil to print the list of objects in the bucket after the second deploy completed successfully.  But gcloud reports the function is still in a goofy state:

```
● % gcloud beta functions describe http
entryPoint: http
httpsTrigger:
  url: https://us-central1-asdf-165014.cloudfunctions.net/http
latestOperation: operations/YXNkZi0xNjUwMTQvdXMtY2VudHJhbDEvaHR0cC80VW1lbmExa0F5Zw
name: projects/asdf-165014/locations/us-central1/functions/http
serviceAccount: asdf-165014@appspot.gserviceaccount.com
sourceArchiveUrl: gs://sls-synk-dev-1495482334612/serverless/synk/dev/1495482335845-2017-05-22T19:45:35.845Z/synk.zip
status: FAILED
timeout: 60s
updateTime: '2017-05-22T19:45:53Z'
● % gsutil ls gs://sls-synk-dev-1495482334612/serverless/synk/dev/
gs://sls-synk-dev-1495482334612/serverless/synk/dev/1495482335845-2017-05-22T19:45:35.845Z/
gs://sls-synk-dev-1495482334612/serverless/synk/dev/1495482416000-2017-05-22T19:46:56.000Z/
● % gcloud beta functions describe http
availableMemoryMb: 256
entryPoint: http
httpsTrigger:
  url: https://us-central1-asdf-165014.cloudfunctions.net/http
latestOperation: operations/YXNkZi0xNjUwMTQvdXMtY2VudHJhbDEvaHR0cC80VW1lbmExa0F5Zw
name: projects/asdf-165014/locations/us-central1/functions/http
serviceAccount: asdf-165014@appspot.gserviceaccount.com
sourceArchiveUrl: gs://sls-synk-dev-1495482334612/serverless/synk/dev/1495482335845-2017-05-22T19:45:35.845Z/synk.zip
status: FAILED
timeout: 60s
updateTime: '2017-05-22T19:45:53Z'
```

I guess yarn doesn't process a `list` properly when using a git repo directly?
```
● % cat yarn.lock | grep serverless
"serverless-google-cloudfunctions@https://github.com/serverless/serverless-google-cloudfunctions.git#master":
  resolved "https://github.com/serverless/serverless-google-cloudfunctions.git#c1b670bc10ce1fda873a91e3c111602
```
