### ISSUE TITLE
Http trigger path ignored by deployment

### ISSUE THREAD

**Issue by fivepointseven** [serverless/serverless-google-cloudfunctions#84]
I have a following function config in `serverless.yml`
```yaml
functions:
  create-account:
    handler: createAccount
    events:
      - http: create-account
```
Yet when the deployment runs, I get:
```
Deployed functions
create-account
  https://us-central1-gcfteststuff.cloudfunctions.net/createAccount
```
In Deployment Manager dashboard the `httpsTrigger` value is set to `url: create-account`. What might be the issue?

**Comment by pmuens** [comment]
Thanks for reporting @fivepointseven 👍

🤔 it looks like the `handler` is used for the `http` event here and not the value of the `http` event definition.

**Comment by fivepointseven** [comment]
But isn't this just the summary that's displayed after the deployment is done?
Actual URL appears to be set up here:
https://github.com/serverless/serverless-google-cloudfunctions/blob/ccd81a56f8d08b8cb30a46d2e23d96c5218828d6/package/lib/compileFunctions.js#L43-L48
and it seems like it's working correctly, but path is still not being set by deployment manager

**Comment by pmuens** [comment]
Thanks for getting back @fivepointseven 👍

🤔 according to the `serverless.yml` in your issue description your path is `create-account` and that's the same path you see in the Deployment Manager dashboard (which is correct in that case).

The URL which is displayed after the deployment was done is wrong and displays `createAccount `. So we should fix the `info` plugin which outputs service information at the end of each deployment, or am I missing something?

**Comment by fivepointseven** [comment]
@pmuens that is like the next step of my issue 😅 
The problem is, that deployment manager receives correct HTTP trigger value, but when function actually gets created, it has a trigger path of handler name
With the serverless.yml from above I expect it to be `https://us-central1-gcfteststuff.cloudfunctions.net/create-account`, but instead the URL is `https://us-central1-gcfteststuff.cloudfunctions.net/createAccount`
I saw a conversation in #78, specifically this comment:
https://github.com/serverless/serverless-google-cloudfunctions/issues/78#issuecomment-318345066
And those kinds of paths don't work for me, it always sets path as the name of handler

**Comment by pmuens** [comment]
@fivepointseven thanks for getting back.

Right now Google will create a fully-fledged API for you. So you cannot set the `path` or `method` (as described in the coversation in #78).

> The problem is, that deployment manager receives correct HTTP trigger value, but when function actually gets created, it has a trigger path of handler name

I'm not sure if I'm following 😅. Could you share your `serverless.yml` and the setup of your CloudFunction (e.g. a screenshot) so that we can see how everything is setup at Googles end?

My assumption is that the `info` command is just wrong.

**Comment by fivepointseven** [comment]
Here's serverless.yml:

```yaml
service: gcftest

provider:
  name: google
  runtime: nodejs
  project: gcftestproject
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  create-account:
    handler: createAccount
    events:
      - http: create-account
```

This is Cloud Functions:
<img width="757" alt="screen shot 2017-09-06 at 4 51 07 pm" src="https://user-images.githubusercontent.com/8418866/30102971-ceb43c78-9323-11e7-802b-d2ee64171572.png">

As you can see, the trigger is the same as handler name.
But here's the same function the Deployment Manager:

<img width="347" alt="screen shot 2017-09-06 at 4 54 39 pm" src="https://user-images.githubusercontent.com/8418866/30103103-3879684a-9324-11e7-81cc-b06d5bc2246f.png">

Where httpTrigger is listed correctly.

So the `info` command is correct, because it displays what the endpoint actually becomes.
The problem is that actual endpoint creation ignores `httpTrigger`. And this is confusing to me because Google allows to set it manually when creating functions in dashboard, and if using function name as endpoint name is by design in Deployment Manager like you're saying, then why would it be listed in the Deployment Manager API documentation -_-

**Comment by pauloddr** [comment]
As it is currently, I can only create Google Functions with names matching their handlers. 

Example:

```javascript
exports.http = (request, response) => {
  response.status(200).send('Hello World!')
}
```

```yaml
service: my-service
...
functions:
  my-service:
    handler: http
    events:
      - http: my-service
```

The above will create a function named "http" and its URL:

https://us-central1-PROJECT_ID.cloudfunctions.net/http

While I would expect a function called "my-service" to be created with the URL:

https://us-central1-PROJECT_ID.cloudfunctions.net/my-service

I think the plugin needs to address this in another way, as in not relying on httpsTrigger, because it clearly has no effect in the function URL. The function name itself does.

I've been manually creating Google Functions and trying to switch to Serverless for deploys, but this issue is preventing me to.

**Comment by samarara** [comment]
Any updates on this? I'm encountering the same issue.

**Comment by jbcpollak** [comment]
I'm having the same problem. In fact, for me I can't seem to rename my function from `http` to anything else:

```
functions:
  my-service:
    handler: http
    events:
      - http: my-service
```

If I change it to `handler: my-service`, I get an error message: `Name in request must be equal to the name of the function.`
