### ISSUE TITLE
Add support for Database events

### ISSUE THREAD

**Issue by fantapop** [serverless/serverless-google-cloudfunctions#86]
It would be great if this supported firebase real time db triggers: 

https://firebase.google.com/docs/reference/functions/functions.database

**Comment by marianofino** [comment]
Hello @fantapop 
For triggering a function whenever it creates new data in realtime database, you should write something like this in the serverless.yml file:
```
myFunction:
  handler: myFunction
  events:
    - event:
        eventType: providers/cloud.firestore/eventTypes/document.update
        resource: projects/<project-id>/databases/(default)/documents/<path-to-document>
```
As I pointed out [here](https://github.com/serverless/serverless-google-cloudfunctions/issues/146#issuecomment-479707759), I wrote an article about it: https://medium.com/ponce-agtech/using-firebase-triggers-in-serverless-framework-ad99594b86fa
